[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

    # CSP policy strict by default, then allow:
    # - `connect-src data:` for download URLs when exporting datasets/slices in h5wasm demo
    # - `script-src 'unsafe-eval'` because of cwise dependency in H5Web
    # - `img-src blob:` for JPEG/PNG images in Raw visualization
    # - `worker-src blob:` for H5WasmLocalFileProvider's inline worker
    Content-Security-Policy = "default-src 'none'; connect-src data:; script-src 'unsafe-eval'; img-src blob:; worker-src blob:"
