name: Lint & Test

on:
  pull_request: # for PRs from forks
  push:
    branches-ignore:
      - 'update-snapshots'

jobs:
  lint:
    runs-on: ubuntu-latest
    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Set up Node 🕹️
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install pnpm ⚙️
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Restore cache 📌
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies ⚙️
        run: pnpm install --frozen-lockfile

      - name: Lint 🤓
        run: pnpm prettier && pnpm lint

  test:
    runs-on: ubuntu-latest
    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Set up Node 🕹️
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install pnpm ⚙️
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Restore cache 📌
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies ⚙️
        run: pnpm install --frozen-lockfile

      - name: Test 👓
        run: pnpm test -- --reporters="default" --reporters="github-actions"
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest
    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Set up Node 🕹️
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install pnpm ⚙️
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Restore cache 📌
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies ⚙️
        run: pnpm install --frozen-lockfile

      - name: Build packages 📦
        run: pnpm packages

      - name: Build demo 🛠️
        run: pnpm build

      - name: Serve ⚡️
        run: pnpm serve & pnpx wait-on http://localhost:5173

      - name: Run Cypress 🌳
        run: pnpm cypress:run
        env:
          CYPRESS_TAKE_SNAPSHOTS: true

      - name: Require approval when new snapshots are created 🔎
        uses: numtide/clean-git-action@v1
        if: success()

      - name: Upload debug screenshots and diffs on failure 🖼️
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress
          path: |
            cypress/debug/
            cypress/snapshots/**/__diff_output__/
