name: Lint & Test

on:
  push:
    branches-ignore:
      - 'update-snapshots'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ⚙️
        uses: bahmutov/npm-install@v1

      - name: Lint 🤓
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ⚙️
        uses: bahmutov/npm-install@v1

      - name: Test 👓
        run: npm test
        env:
          CI: true

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Cypress binary 💾
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install ⚙️
        uses: bahmutov/npm-install@v1

      - name: Build 🛠️
        run: npm run build

      - name: Serve ⚡️
        run: npx serve -s build -l 3000 & npx wait-on http://localhost:3000

      - name: Run Cypress 🌳
        run: npm run cypress:run
        env:
          CYPRESS_TAKE_SNAPSHOTS: true

      - name: Upload debug screenshots and diffs on failure 🖼️
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress
          path: |
            cypress/debug/
            cypress/snapshots/**/__diff_output__/
