name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v2

      - name: Match tag to package version 🧐
        id: packageVersion
        uses: geritol/match-tag-to-package-version@0.1.0
        env:
          TAG_PREFIX: refs/tags/v

      - name: Use Node 16 🕹️
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ⚙️
        uses: bahmutov/npm-install@v1
      - name: Install ⚙️
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages

      - name: Build 🛠️
        run: cd packages && yarn build

      - name: Set @h5web/app version 📌
        uses: reedyuk/npm-version@1.0.1
        with:
          version: ${{ steps.packageVersion.outputs.PACKAGE_VERSION }}
          package: 'packages/app/dist'

      - name: Set @h5web/lib version 📌
        uses: reedyuk/npm-version@1.0.1
        with:
          version: ${{ steps.packageVersion.outputs.PACKAGE_VERSION }}
          package: 'packages/lib/dist'

      - name: Publish @h5web/app 🥳
        uses: JS-DevTools/npm-publish@v1
        with:
          package: 'packages/app/dist/package.json'
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Publish @h5web/lib 🤩
        uses: JS-DevTools/npm-publish@v1
        with:
          package: 'packages/lib/dist/package.json'
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Build Storybook 🛠️
        run: yarn storybook:build
        env:
          INPUT_TOKEN: '' # workaround for https://github.com/JS-DevTools/npm-publish/issues/15

      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
